version: '3'
services:
  bpmn-python-3.6:
    build:
      context: ./3.6
      dockerfile: Dockerfile-3.6
    stdin_open: true
    tty: true
    volumes:
      - shared_data:/app/shared_data
  bpmn-python-3.12:
    build:
      context: ./3.12
      dockerfile: Dockerfile-3.12
    stdin_open: true
    tty: true
    volumes:
      - shared_data:/app/shared_data

volumes:
  shared_data: