services:
  diagbp:
    build:
      context: ./
    volumes:
      - ./3.6:/app/3.6 #to remove
      - ./3.11:/app/3.11 #to remove      
      - uploads:/app/shared
      - logs:/app/logs
      - json:/app/json

  interface:
    build:
      context: ./interface
    volumes:
      - ./interface/scripts:/app/scripts #to remove
      - ./interface/templates:/app/templates #to remove
      - ./interface/static:/app/static #to remove
      - uploads:/app/uploads
      - logs:/app/logs
      - json:/app/json
    ports:
      - "5000:5000"
    depends_on:
      - diagbp

volumes:
  uploads:
  logs:
  json: